[package]
name = "op-alloy-example"
version = "0.1.0"
edition = "2021"

[dependencies]
eyre = "0.6.12"
tokio = { version = "1.43.0", features = ["rt-multi-thread"] }

alloy-eips = "0.11.0"
alloy-provider = "0.11.0"
alloy-rpc-types = "0.11.0"
op-alloy-network = "0.10.3"
